name: CI-CD Pipeline for MERN App

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Ensure full branch history is fetched

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "latest"

            - name: Install backend dependencies
              run: |
                  cd server
                  npm install

            - name: Install frontend dependencies
              run: |
                  cd frontend
                  npm install

            - name: Run tests
              env:
                  CI: true
                  NODE_ENV: test
                  dbURL: ${{ secrets.DBURL }}
              run: |
                  cd server
                  npm test
