name: CI-CD Pipeline for MERN App

on:
    pull_request: # Trigger on pull requests targeting the main branch
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "latest"

            - name: Install backend dependencies
              run: |
                  cd server
                  npm install

            - name: Install frontend dependencies
              run: |
                  cd frontend
                  npm install

            - name: Run tests
              env:
                  CI: true
                  NODE_ENV: test
                  dbURL: ${{ secrets.DBURL }}
              run: |
                  cd server
                  npm test

            - name: Merge pull request if tests pass
              if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == false }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch
